"""add uq index on merchants name

Revision ID: 0c03a7d83c23
Revises: 2cb327187492
Create Date: 2025-11-23 17:17:20.335685

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0c03a7d83c23"
down_revision: Union[str, Sequence[str], None] = "2cb327187492"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("merchants_name_idx", "merchants", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("merchants_name_idx", table_name="merchants")
    # ### end Alembic commands ###
