"""add currency to tranfers

Revision ID: 2cb327187492
Revises: c2e083371ca9
Create Date: 2025-11-23 16:11:23.119428

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2cb327187492"
down_revision: Union[str, Sequence[str], None] = "c2e083371ca9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transfers", sa.Column("currency", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transfers", "currency")
    # ### end Alembic commands ###
