"""add amount to balance table

Revision ID: 3e299df8011c
Revises: 0c03a7d83c23
Create Date: 2025-11-23 17:58:13.551273

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e299df8011c"
down_revision: Union[str, Sequence[str], None] = "0c03a7d83c23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balances",
        sa.Column(
            "amount", sa.NUMERIC(precision=12, scale=2), server_default="0.00", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("balances", "amount")
    # ### end Alembic commands ###
