"""add idempotency ket to transfers

Revision ID: 6f12baf6b566
Revises: ee579c370e7b
Create Date: 2025-11-23 19:27:37.804084

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f12baf6b566"
down_revision: Union[str, Sequence[str], None] = "ee579c370e7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "balances",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=10),
        type_=sa.NUMERIC(precision=12, scale=8),
        existing_nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    op.add_column("transfers", sa.Column("idempotency_key", sa.String(), nullable=False))
    op.alter_column(
        "transfers",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=10),
        type_=sa.NUMERIC(precision=12, scale=8),
        existing_nullable=False,
    )
    op.create_index(
        "transfers_idempotency_key_uq_idx", "transfers", ["idempotency_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("transfers_idempotency_key_uq_idx", table_name="transfers")
    op.alter_column(
        "transfers",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=8),
        type_=sa.NUMERIC(precision=12, scale=10),
        existing_nullable=False,
    )
    op.drop_column("transfers", "idempotency_key")
    op.alter_column(
        "balances",
        "amount",
        existing_type=sa.NUMERIC(precision=12, scale=8),
        type_=sa.NUMERIC(precision=12, scale=10),
        existing_nullable=False,
        existing_server_default=sa.text("0.00"),
    )
    # ### end Alembic commands ###
