"""create base tables

Revision ID: c2e083371ca9
Revises:
Create Date: 2025-11-23 15:23:42.637230

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2e083371ca9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("percent_fee", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "balances",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], name="merchants_id_fk"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "balances_merchant_id_uq_idx", "balances", ["merchant_id", "currency"], unique=True
    )
    op.create_table(
        "transfers",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column(
            "created",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column(
            "updated",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(now() at time zone 'utc')"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("from_merchant_id", sa.UUID(), nullable=False),
        sa.Column("to_merchant_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.Column("percent_fee", sa.NUMERIC(precision=12, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_merchant_id"], ["merchants.id"], name="transfers_from_merchants_id_fk"
        ),
        sa.ForeignKeyConstraint(
            ["to_merchant_id"], ["merchants.id"], name="transfers_to_merchants_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "transfers_from_merchant_id_idx", "transfers", ["from_merchant_id"], unique=False
    )
    op.create_index("transfers_to_merchant_id_idx", "transfers", ["to_merchant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("transfers_to_merchant_id_idx", table_name="transfers")
    op.drop_index("transfers_from_merchant_id_idx", table_name="transfers")
    op.drop_table("transfers")
    op.drop_index("balances_merchant_id_uq_idx", table_name="balances")
    op.drop_table("balances")
    op.drop_table("merchants")
    # ### end Alembic commands ###
