"""edit amount float

Revision ID: ee579c370e7b
Revises: 3e299df8011c
Create Date: 2025-11-23 18:27:44.433655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee579c370e7b'
down_revision: Union[str, Sequence[str], None] = '3e299df8011c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('balances', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('transfers', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.NUMERIC(precision=12, scale=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfers', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('balances', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=8),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    # ### end Alembic commands ###
